package com.gegprifti.android.numbertheoryalgorithms.algorithms.common;


public enum AlgorithmName {
    CALCULATOR_ADDITION,
    CALCULATOR_SUBTRACTION,
    CALCULATOR_MULTIPLICATION,
    CALCULATOR_DIVISION,
    CALCULATOR_POWER,
    CALCULATOR_ROOT,
    CALCULATOR_GCD,
    CALCULATOR_LCM,
    CALCULATOR_MOD,
    CALCULATOR_MOD_INVERSE,
    CALCULATOR_IS_PROBABLE_PRIME,
    CALCULATOR_FACTORIAL,
    CALCULATOR_EULER_PHI,
    CALCULATOR_NEXT_PROBABLE_PRIME,
    CALCULATOR_NEXT_PROBABLE_TWIN_PRIME_PAIR,
    BINARY_QUADRATIC_FORM,
    BINARY_QUADRATIC_FORM_1,
    BINARY_QUADRATIC_FORM_2,
    EUCLIDEAN_ALGORITHM,
    EXTENDED_EUCLIDEAN_ALGORITHM,
    LINEAR_CONGRUENCE_IN_ONE_VARIABLE,
    LINEAR_CONGRUENCE_IN_TWO_VARIABLES,
    LINEAR_DIOPHANTINE_EQUATION_IN_TWO_VARIABLES,
    TONELLI_SHANKS_ALGORITHM,
    MOD_FACTORS,
    MOD_FACTORS_COUNT,
    PRIMES_LIST
}
